# Generated by Django 3.1.4 on 2021-01-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duplas', '0003_auto_20201210_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Nome')),
                ('surname', models.CharField(blank=True, max_length=127, null=True, verbose_name='Sobrenome')),
                ('gender', models.CharField(choices=[('', 'Selecione'), ('M', 'Masculino'), ('F', 'Feminino')], max_length=20, verbose_name='Sexo')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Duplas',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
