# Generated by Django 3.1.4 on 2021-01-07 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duplas', '0004_auto_20210107_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duplas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('integrante_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primeiro_integrante', to='duplas.integrante')),
                ('integrante_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segundo_integrante', to='duplas.integrante')),
            ],
        ),
    ]
